#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { spawnSync } from 'node:child_process'
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from 'node:path'
import { createRequire } from 'node:module'
import { pathToFileURL } from 'node:url'
import { build as esbuild } from 'esbuild'
import { fromBinary } from '@bufbuild/protobuf'
import { FileDescriptorSetSchema } from '@bufbuild/protobuf/wkt'

const require = createRequire(import.meta.url)
const packageRoot = dirname(require.resolve('@bufbuild/buf/package.json'))
const protocGenEsRoot = dirname(require.resolve('@bufbuild/protoc-gen-es/package.json'))
const bufProgram = join(packageRoot, 'bin', 'buf')
const protocGenEsProgram = join(protocGenEsRoot, 'bin', 'protoc-gen-es')

export async function runScalpelPlugin(command, projectPath = '.') {
  const projectDir = resolve(projectPath)
  const packagePath = join(projectDir, 'package.json')
  const pkg = readJson(packagePath)
  const config = pkg.scalpelPlugin
  if (!config || typeof config !== 'object') throw new Error(`${packagePath} does not declare scalpelPlugin`)
  validateConfig(projectDir, config, command)
  validateManifestBindings(projectDir, config)

  switch (command) {
    case 'generate':
      generateContracts(projectDir, config, false)
      return
    case 'check':
      generateContracts(projectDir, config, true)
      if (config.entry) await bundlePlugin(projectDir, config, true)
      return
    case 'build':
      generateContracts(projectDir, config, false)
      await bundlePlugin(projectDir, config, false)
      return
    case 'pack':
      generateContracts(projectDir, config, false)
      await bundlePlugin(projectDir, config, false)
      packPlugin(projectDir, config)
      return
    default:
      throw new Error(`unknown command "${command}" (expected generate, check, build, or pack)`)
  }
}

function generateContracts(projectDir, config, check) {
  for (const contract of config.contracts ?? []) {
    const temp = mkdtempSync(join(tmpdir(), 'scalpel-plugin-'))
    try {
      const generatedTemp = join(temp, 'generated')
      const input = contract.source ? resolve(projectDir, contract.source) : resolve(projectDir, contract.input)
      if (!existsSync(input)) throw new Error(`Protobuf input does not exist: ${input}`)

      if (contract.source) {
        const descriptorTemp = join(temp, 'contract.binpb')
        runNodeProgram(bufProgram, ['build', input, '--as-file-descriptor-set', '--output', descriptorTemp], projectDir)
        validateDescriptor(descriptorTemp, contract.service)
        syncFile(descriptorTemp, resolve(projectDir, contract.descriptor), check, 'descriptor')
      } else {
        validateDescriptor(input, contract.service)
      }

      const template = JSON.stringify({
        version: 'v2',
        plugins: [
          {
            local: [process.execPath, protocGenEsProgram],
            out: '.',
            opt: ['target=ts'],
          },
        ],
      })
      runNodeProgram(bufProgram, ['generate', input, '--template', template, '--output', generatedTemp], projectDir)
      syncDirectory(generatedTemp, resolve(projectDir, contract.generated), check)
    } finally {
      rmSync(temp, { recursive: true, force: true })
    }
  }
}

async function bundlePlugin(projectDir, config, check) {
  const bundlePath = resolve(projectDir, config.bundle ?? 'plugin.js')
  const result = await esbuild({
    absWorkingDir: projectDir,
    entryPoints: [relative(projectDir, resolve(projectDir, config.entry))],
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    external: [
      '@scalpelpoe/plugin-sdk',
      'react',
      'react-dom',
      'react-dom/client',
      'react-dom/server',
      'react/jsx-runtime',
    ],
    banner: { js: '// Generated by scalpel-plugin. Do not edit.' },
  })
  const bytes = result.outputFiles[0].contents
  if (check) {
    if (!existsSync(bundlePath) || !equalBytes(readFileSync(bundlePath), bytes)) {
      throw new Error(`generated bundle is stale: ${bundlePath}`)
    }
    return
  }
  mkdirSync(dirname(bundlePath), { recursive: true })
  writeFileSync(bundlePath, bytes)
}

function packPlugin(projectDir, config) {
  const manifestPath = resolve(projectDir, config.manifest)
  const manifest = readJson(manifestPath)
  let executable = null
  if (config.native) {
    const targetName = config.native.target ?? 'win32-x64'
    if (targetName === 'win32-x64' && (process.platform !== 'win32' || process.arch !== 'x64')) {
      throw new Error('native target win32-x64 must be packed on a Windows x64 host')
    }
    executable = buildNative(projectDir, config.native)
    const target = manifest.nativeBackend?.targets?.[targetName]
    if (!target) throw new Error(`manifest does not declare native target ${targetName}`)
    if (typeof target.file !== 'string' || basename(target.file) !== target.file) {
      throw new Error('native target file must be a root-level filename')
    }
    const bytes = readFileSync(executable)
    target.sha256 = createHash('sha256').update(bytes).digest('hex')
  }

  const outDir = resolve(projectDir, config.outDir ?? 'dist')
  rmSync(outDir, { recursive: true, force: true })
  mkdirSync(outDir, { recursive: true })
  writeFileSync(join(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`)
  copyFileSync(resolve(projectDir, config.bundle ?? 'plugin.js'), join(outDir, 'plugin.js'))
  if (manifest.api) copyFileSync(resolve(projectDir, manifest.api.contract), join(outDir, manifest.api.contract))
  if (manifest.nativeBackend) {
    copyFileSync(resolve(projectDir, manifest.nativeBackend.contract), join(outDir, manifest.nativeBackend.contract))
    if (!executable) throw new Error('manifest declares nativeBackend but scalpelPlugin.native is missing')
    const target = manifest.nativeBackend.targets[config.native.target ?? 'win32-x64']
    copyFileSync(executable, join(outDir, target.file))
  }
}

function buildNative(projectDir, native) {
  const cargoManifest = resolve(projectDir, native.cargoManifest)
  const result = spawnSync(
    'cargo',
    ['build', '--release', '--message-format=json-render-diagnostics', '--manifest-path', cargoManifest],
    { cwd: projectDir, encoding: 'utf8', windowsHide: true },
  )
  if (result.stderr) process.stderr.write(result.stderr)
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`cargo build failed with status ${String(result.status)}`)
  let executable = null
  for (const line of result.stdout.split(/\r?\n/)) {
    if (!line) continue
    let message
    try {
      message = JSON.parse(line)
    } catch {
      continue
    }
    if (
      message.reason === 'compiler-artifact' &&
      message.target?.name === native.binary &&
      message.target?.kind?.includes('bin') &&
      typeof message.executable === 'string'
    ) {
      executable = message.executable
    }
  }
  if (!executable) throw new Error(`cargo did not report executable for binary ${native.binary}`)
  return executable
}

function syncFile(source, destination, check, kind) {
  const bytes = readFileSync(source)
  if (check) {
    if (!existsSync(destination) || !equalBytes(readFileSync(destination), bytes)) {
      throw new Error(`generated ${kind} is stale: ${destination}`)
    }
    return
  }
  mkdirSync(dirname(destination), { recursive: true })
  writeFileSync(destination, bytes)
}

function syncDirectory(source, destination, check) {
  if (check) {
    const expected = directoryFiles(source)
    const actual = existsSync(destination) ? directoryFiles(destination) : []
    if (expected.join('\0') !== actual.join('\0')) throw new Error(`generated files are stale: ${destination}`)
    for (const name of expected) {
      if (!equalBytes(readFileSync(join(source, name)), readFileSync(join(destination, name)))) {
        throw new Error(`generated file is stale: ${join(destination, name)}`)
      }
    }
    return
  }
  rmSync(destination, { recursive: true, force: true })
  mkdirSync(dirname(destination), { recursive: true })
  cpSync(source, destination, { recursive: true })
}

function directoryFiles(root) {
  const files = []
  const visit = (directory) => {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name)
      if (entry.isDirectory()) visit(path)
      else if (entry.isFile()) files.push(relative(root, path).replaceAll('\\', '/'))
    }
  }
  visit(root)
  return files.sort()
}

function runNodeProgram(program, args, cwd) {
  const result = spawnSync(process.execPath, [program, ...args], { cwd, encoding: 'utf8', windowsHide: true })
  if (result.stdout) process.stdout.write(result.stdout)
  if (result.stderr) process.stderr.write(result.stderr)
  if (result.error) throw result.error
  if (result.status !== 0) throw new Error(`${basename(program)} failed with status ${String(result.status)}`)
}

function validateConfig(projectDir, config, command) {
  if (command !== 'generate' && command !== 'check') {
    if (typeof config.manifest !== 'string' || !config.manifest) throw new Error('scalpelPlugin.manifest is required')
    if (typeof config.entry !== 'string' || !config.entry) throw new Error('scalpelPlugin.entry is required')
  }
  if (config.contracts !== undefined && !Array.isArray(config.contracts)) {
    throw new Error('scalpelPlugin.contracts must be an array')
  }
  const generatedDirectories = new Set()
  for (const contract of config.contracts ?? []) {
    if (!contract || typeof contract !== 'object') throw new Error('each contract configuration must be an object')
    if (Boolean(contract.source) === Boolean(contract.input)) {
      throw new Error('each contract must declare exactly one of source or input')
    }
    if (contract.source && typeof contract.descriptor !== 'string') {
      throw new Error('source contracts must declare descriptor')
    }
    if (typeof contract.generated !== 'string') throw new Error('each contract must declare generated')
    if (contract.service !== undefined && typeof contract.service !== 'string') {
      throw new Error('contract.service must be a fully qualified Protobuf service name')
    }
    if (contract.source) assertProjectPath(projectDir, contract.source, 'contract.source')
    if (contract.descriptor) assertProjectPath(projectDir, contract.descriptor, 'contract.descriptor')
    const generated = assertProjectPath(projectDir, contract.generated, 'contract.generated')
    if (generatedDirectories.has(generated)) throw new Error('contracts must use distinct generated directories')
    generatedDirectories.add(generated)
  }
  if (config.manifest) assertProjectPath(projectDir, config.manifest, 'scalpelPlugin.manifest')
  if (config.entry) assertProjectPath(projectDir, config.entry, 'scalpelPlugin.entry')
  assertProjectPath(projectDir, config.bundle ?? 'plugin.js', 'scalpelPlugin.bundle')
  assertProjectPath(projectDir, config.outDir ?? 'dist', 'scalpelPlugin.outDir')
  if (config.native?.cargoManifest) {
    assertProjectPath(projectDir, config.native.cargoManifest, 'scalpelPlugin.native.cargoManifest')
  }
}

function validateDescriptor(path, selectedService) {
  if (!selectedService) return
  const descriptor = fromBinary(FileDescriptorSetSchema, readFileSync(path))
  for (const file of descriptor.file) {
    for (const service of file.service) {
      const typeName = file.package ? `${file.package}.${service.name}` : service.name
      if (typeName !== selectedService) continue
      const streaming = service.method.find((method) => method.clientStreaming || method.serverStreaming)
      if (streaming) throw new Error(`streaming Protobuf method is unsupported: ${selectedService}.${streaming.name}`)
      return
    }
  }
  throw new Error(`Protobuf service not found in descriptor: ${selectedService}`)
}

function validateManifestBindings(projectDir, config) {
  if (!config.manifest) return
  const manifestPath = resolve(projectDir, config.manifest)
  if (!existsSync(manifestPath)) throw new Error(`manifest does not exist: ${manifestPath}`)
  const manifest = readJson(manifestPath)
  for (const declaration of [manifest.api, manifest.nativeBackend]) {
    if (!declaration) continue
    if (typeof declaration.contract !== 'string' || basename(declaration.contract) !== declaration.contract) {
      throw new Error('manifest contracts must be root-level filenames')
    }
    const contract = (config.contracts ?? []).find(
      (candidate) => candidate.descriptor && resolve(projectDir, candidate.descriptor) === resolve(projectDir, declaration.contract),
    )
    if (!contract) throw new Error(`scalpelPlugin.contracts does not generate ${declaration.contract}`)
    if (contract.service !== declaration.service) {
      throw new Error(`configured service does not match manifest service ${declaration.service}`)
    }
  }
}

function assertProjectPath(projectDir, value, field) {
  if (typeof value !== 'string' || value.length === 0) throw new Error(`${field} must be a non-empty path`)
  const path = resolve(projectDir, value)
  const fromProject = relative(projectDir, path)
  if (!fromProject || fromProject === '..' || fromProject.startsWith(`..${sep}`) || isAbsolute(fromProject)) {
    throw new Error(`${field} must stay inside the plugin project`)
  }
  return path
}

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'))
}

function equalBytes(left, right) {
  return left.length === right.length && left.equals(Buffer.from(right))
}

function argument(name) {
  const index = process.argv.indexOf(name)
  return index === -1 ? null : process.argv[index + 1]
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  const command = process.argv[2]
  runScalpelPlugin(command, argument('--project') ?? '.')
    .then(() => {
      process.stdout.write(`scalpel-plugin ${command} completed\n`)
    })
    .catch((error) => {
      process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
      process.exitCode = 1
    })
}
