// Generated by scripts/build-plugin-service-examples.mjs. Do not edit.

// plugin-service-examples/greeting-consumer/src/generated/greeting-provider-client.ts
var GREETING_PROVIDER_PLUGIN_ID = "greeting-provider";
var GREETING_PROVIDER_API_VERSION = "1.0.0";
var GreetingProviderClient = class {
  constructor(rpc) {
    this.rpc = rpc;
  }
  /** Create a greeting for an exile. */
  async greet(params) {
    return this.rpc.call("greet", params);
  }
};
function getGreetingProviderClient(ctx) {
  const rpc = ctx.plugins.get(GREETING_PROVIDER_PLUGIN_ID);
  if (!rpc) return null;
  if (rpc.apiVersion !== GREETING_PROVIDER_API_VERSION) {
    throw new Error(
      `Plugin "${GREETING_PROVIDER_PLUGIN_ID}" exposes API ${rpc.apiVersion}; expected ${GREETING_PROVIDER_API_VERSION}`
    );
  }
  return new GreetingProviderClient(rpc);
}
function requireGreetingProviderClient(ctx) {
  const client = getGreetingProviderClient(ctx);
  if (!client) throw new Error(`Required plugin "${GREETING_PROVIDER_PLUGIN_ID}" is unavailable`);
  return client;
}

// plugin-service-examples/greeting-consumer/src/plugin.ts
var activate = (ctx) => {
  const greetings = requireGreetingProviderClient(ctx);
  ctx.registerTab({
    label: "Greeting Consumer",
    icon: '<svg viewBox="0 0 16 16"><path d="M2 3h12v8H8l-3 3v-3H2z" fill="currentColor"/></svg>',
    render(container) {
      container.innerHTML = `
        <section style="padding: 16px">
          <h2>Greeting Consumer</h2>
          <button type="button" data-ask-provider>Ask provider</button>
          <p data-provider-result>Waiting for a call.</p>
        </section>
      `;
      const button = container.querySelector("[data-ask-provider]");
      const result = container.querySelector("[data-provider-result]");
      const ask = async () => {
        result.textContent = "Calling...";
        try {
          const response = await greetings.greet({ name: "Exile" });
          result.textContent = `${response.message} (${response.calls} call)`;
        } catch (error) {
          result.textContent = error instanceof Error ? error.message : String(error);
        }
      };
      button.addEventListener("click", ask);
      return () => button.removeEventListener("click", ask);
    }
  });
};
var plugin_default = activate;
export {
  plugin_default as default
};
