export const CHANGELOG: { version: string; notes: string[] }[] = [
  {
    version: '0.9.17',
    notes: [
      'Added a live mirror whiteboard element that pins a region of the game window and shows it in real time, with your placement persisted between sessions.',
      "Plugins you've opted into now update themselves silently in the background, no manual reinstall.",
      'Scalpel now switches between PoE1 and PoE2 in place with no app relaunch (s/o Dan!).',
      'Added a base defence percentile row to PoE1 price-check.',
      'Added premium mods for the Rite of Passage spirit variants.',
      'Maps and waystones now show a modifier count in place of the old chip.',
      'Updated the PoE2 regex tools for the new league: tablet types and rare matching, bounded value matching, waystone revives and rarity, and vendor fixes.',
      'Added a right-click "Set Learned Preference" menu on price-check rows to pin a filter on or off; pins survive Reset Learning.',
      '"Grants Skill" price-check rows now take part in learned defaults.',
      'Weapon price-check now defaults to Total DPS, with Physical and Elemental DPS off.',
      'Hotkeys can now be bound to numpad keys.',
      'Refreshed the item tier data.',
      'The title bar now shows a plain version number, no more Beta tag or PoE suffix.',
      "Fixed runemastered and runeforged uniques (like Runeseeker's Call) price-checking against the plain base instead of the rune variant, so no listings came back.",
      'Fixed tablet mods price-checking against dead, delisted, or wrong-pool trade stats.',
      'Fixed unidentified unique maps price-checking by their base type instead of the actual unique.',
      'Fixed increased flask Duration being dropped from price-check on "Life Flasks" and "Mana Flasks".',
      'Fixed rune socket count being thrown off by special runes that take up a socket.',
      'Fixed an invisible pinned distance-zone window blocking mouse clicks in town.',
      'Fixed hybrid resistance mods with signed (+/-) roll ranges not reading their bounds in price-check.',
      'Fixed live mirrors turning invisible after a game restart.',
      'Fixed pressing Esc to close the overlay also opening the game menu.',
      'Fixed catalyst quality not scaling implicit rolls in price-check.',
      'Fixed PoE2 Mageblood price-check missing its duplicated Legacy charms.',
      'Fixed the regex tool\'s waystone tier pattern matching numbers from other lines (like "Uncut Skill Gem (Level 16)"), and resynced the tablet regex data.',
      'Fixed the collapsed cheat-sheet bar shoving its header out of view on a zone change; restoring now puts it back exactly where it was.',
    ],
  },
  {
    version: '0.9.16',
    notes: [
      'Plugin developers can now make parts of a click-through annotation overlay clickable via the new ctx.setInteractiveRegion capability.',
      'PoE2 socketed runes now apply in price-check, including pseudo totals like "Total Elemental Resistance".',
      'Fixed the "Break increased Armour" glove enchant matching the wrong "increased Armour" stat in price-check.',
    ],
  },
  {
    version: '0.9.15',
    notes: [
      'PoE2 waystone price-check now defaults to yield chips on and difficulty affixes off.',
      'Tidied the collapsed cheat-sheet bar: hid the tabs and thumbnail-size control, locked edge-resizing, and muted the hover-preview flash.',
      'Plugin developers can now read the live per-game league list via the new ctx.getLeagues capability.',
      'Fixed cheat-sheets drifting off-screen when minimized and restored at fractional display scaling.',
      'Fixed the league list occasionally failing to load on a Cloudflare challenge.',
      'Fixed tablets with an "additional Abyss" mod price-checking against the wrong trade stat.',
      'Fixed waystone price-check searches breaking from a stray base-type chip.',
      'Renamed the "Magic Monsters" and "Rare Monsters" waystone price-check rows to "Monster Effectiveness" and "Monster Rarity" to match the in-game relabel.',
      'Fixed fractured mods not registering in the price checker on chat-linked or basic-copy items.',
      "Fixed global charm-slot grants (like the Elevore helmet) price-checking against the belt's charm-slot stat.",
      'Fixed PoE2 price-check breaking after a Path of Exile trade-site data change.',
    ],
  },
  {
    version: '0.9.14',
    notes: [
      'Added a "Grants Skill" filter and item level to the trade results, and fixed magic item names there.',
      'Added price-check support for "uses remaining" (charges), on by default.',
      'Added related-item suggestions to PoE2 price-check results.',
      'Added a unique-specific price-check override layer for PoE1 and PoE2.',
      'Plugins now update in place with a live hot-swap, no relaunch needed.',
      "Plugin developers can now capture the game window via ctx.captureGameWindow to run their own OCR, and register chrome-less click-through annotation overlays (mode: 'annotation').",
      'Consolidated all hotkeys and macros into the Macros tab in settings, synced to their origin location.',
      'Desecrated mods now show in trade results (in green!).',
      'Price-check now shows the divine value in ex/chaos, and ex/chaos as a fraction of a divine.',
      'Added PoE2 gem socket count as a default-on price-check row.',
      'Added the PoE2 trial key area level as a price-check row.',
      "Fixed removing a hotkey from a plugin's hotkey component.",
      'Fixed the surrounded mod on Constricting Command, and made it a default-checked premium mod.',
      'Fixed assorted tablet issues, including a premium mod on a unique and negative roll handling.',
      'Clarified the filter UI so hiding and showing tiers reads distinctly from retiering items.',
      'Fixed waystones searching in bulk. They now only bulk-search when white.',
      'Re-enabled five PoE2 waystone endgame filters now that trade indexes them.',
      'Fixed trade searches occasionally failing on a Cloudflare challenge from a stray anonymous session cookie. And by fixed I mean, kind of. Logged-out users now get nudged to log in. Which does actually "fix" it.',
      'Fixed PoE2 item level and quality chips being silently ignored in price-check searches.',
      'Fixed PoE2 equipped gem level using the inflated displayed level instead of base plus corruption.',
      'Fixed "+# to Level of ..." gem mods so they price-check at the exact roll.',
      'Fixed weapon "reduced Attack Speed" not matching its trade stat.',
      'Fixed Wraeclast Besieged chase mods to price-check by their exact rolled value.',
      'Fixed hotkeys bound to international and OEM keys (æ, ;, and the like) not firing.',
      'Fixed the "Grants Skill" filter matching the wrong trade stat for Blink, Lightning Bolt, and Decompose.',
    ],
  },
  {
    version: '0.9.13',
    notes: [
      'Massive changes to make filter editing cleaner and less error prone.',
      'Filters now auto-repair on load if they get damaged, with a reversible checkpoint so the change can be undone.',
      'Added a Reset Filter button that restores your local copy back to the online baseline.',
      'Added a "Load online filter in-game to sync" banner when the filter cache is empty.',
      'Added a collapsible Filter Changes list and a Debug Log viewer to the filter history view.',
      'Added language support (English, Spanish, German) with a locale picker that persists across sessions.',
      'Added a PoE2 waystone/tablet Trade tab with refreshed waystone data and a Quantity & yield section.',
      'Added a PoE2 Relic regex tab for Trial of the Sekhemas relic prefixes and suffixes.',
      'Added condition groups to the PoE2 Vendor regex tab: conditions in a group match with OR, separate groups all match (AND).',
      "Added an experimental update channel you can opt into for early builds. But don't.",
      'Updated installer to not allow the troublesome install location for all users.',
      'Plugin developers can now read poe.ninja prices read-only via the new ctx.prices capability.',
      'Perfect or overrolled unique affixes are now checked by default in the price checker.',
      'Price-check defaults are now tier-aware: top-tier rolls turn on and search the low end of their bracket, while sub-par rolls on high item-level gear stay off.',
      'Build-enabling premium mods on specific uniques can be added to be checked by default - propose edits in premium-mods.json and submit a PR.',
      'Added price-check support for runeforged and runemastered bases.',
      'Negative or detrimental rolls are off by default, and sign-flipped reduced-range rolls are no longer flagged as perfect.',
      'Raw attribute rolls now surface on their own unless another life or mana mod accumulates them, and hybrid attribute rolls are shown instead of being partly folded into a pseudo.',
      'Learned price-check preferences reset once so everyone picks up the new defaults.',
      'Default hotkeys no longer include Shift.',
      'Fixed game targeting/evaluation on a fresh start.',
      'Fixed first-run setup leaving the overlay attached to the wrong game; it now relaunches automatically after you pick your game.',
      'Fixed exceptional white items not price checking correctly.',
      'Fixed double-rarity items pricing incorrectly by summing duplicate copies of the same roll; rarity is now on by default in PoE2.',
      'Fixed open affix chips searching their minimum instead of the actual open affix count.',
      'Fixed charm and flask increased Duration not matching its trade stat.',
      'Fixed issue with enchants on bows in price checker.',
      'Fixed the PoE2 price-audit slider baseline label showing "c" instead of "ex".',
      'Fixed PoE2 life regen ranking too high in the price checker.',
      'Fixed issue with base types missing causing parsing to sometimes break.',
      'Fixed The Taming ring in PoE2 and added its trade icon.',
      "Fixed clicking a specific unidentified unique searching by base type instead of that unique's name.",
      'Fixed some mods (such as leech) not scrubbing across their tier range in the price checker.',
      'Fixed PoE2 gem quality not showing in price-check results, and hid the PoE1 only transfigured-gem chip.',
      'Fixed sometimes grabbing the wrong poe.ninja price for uniques.',
    ],
  },
  {
    version: '0.9.12',
    notes: [
      'Added support for all the new items in PoE2 0.5.',
      'Added an Extra Features page (on by default, hideable) to gather the optional tools in one place.',
      'Added draggable tier chips that scrub price-check affix minimums across their roll range.',
      'Added a "Damage" weapon stat to the price checker for builds where attack speed does not matter (off by default).',
      'Added PoE2 "Damage as Extra" pseudo rows that sum your elemental and chaos as-extra affixes.',
      "Added support for unidentified item tiers in the price checker, defaulting to the tier's min and max values.",
      'Added support for plus-or-minus affix lines in the price checker.',
      'Added hover price tooltips across the price-check chips and a current-price footer on the poe.ninja graph.',
      "Added an onboarding tip nudging WASD players toward a hotkey that doesn't share a movement key.",
      'Added the ability to hide plugin tabs in settings like normal tabs can be.',
      'Unidentified unique candidates now show their value in divines once it exceeds one divine.',
      'White, mirrored, and corrupted items no longer show price-check chips that cannot apply to them.',
      'Fixed PoE2 corruption enchantments and anointments not price checking.',
      'Fixed PoE2 crafted mods being miscolored and counted as an open affix in the price checker.',
      'Fixed a multiline mod (such as Yoke of Suffering) being parsed as three separate affixes.',
      'Fixed Voices jewels dropping their "Allocates ... Sinister Jewel sockets" line in the price checker.',
      'Fixed unidentified uniques being searched by name instead of base type.',
      'Fixed the unidentified unique candidates panel collapsing when you select a filter.',
      "Fixed unusable items (such as runes raising a requirement you can't meet) shifting the item name and breaking price checks.",
      'Fixed the base chip flickering and shifting the layout when toggling the mirrored filter.',
      'Fixed profile loading causing the incorrect cheat sheet prefabs to show.',
      'Fixed a layout shift when typing in the macro input.',
      'Dev mode now has its own settings tab (in the app, not the overlay) instead of a hidden toggle.',
      'Plugin developers can now remove their unpacked plugins.',
    ],
  },
  {
    version: '0.9.11',
    notes: [
      'Added runic ward support to the price checker.',
      'Added support for decimal affix values in the price checker.',
      'Added a vendor regex tab and a tablet regex tab in PoE2.',
      'Added a crafting-ready chip, now on by default for PoE2 trade.',
      'Trade search now re-runs on hover when you have changed filters since the last search.',
      'Added charm support to belts.',
      'Regex strings now save automatically.',
      'More regex chip UX cleanup.',
      'Fixed whiteboard rulers causing lag in passthrough.',
      'Fixed various local mods not price checking correctly.',
      'Fixed an Oxford comma breaking hybrid mod price-check matching.',
      'Fixed magic items showing more than one open prefix or suffix chip.',
      'Fixed desecrated and unknown mod qualifiers merging affixes together.',
      'Fixed copying an equipped item failing when the hotkey holds Shift.',
    ],
  },
  {
    version: '0.9.10',
    notes: [
      'Added a regex remote sister overlay you can bind to a hotkey, so your regex strings can pop out on demand.',
      'Reworked the regex UX that nearly everyone hated.',
      'Added a Chaos-only price option to PoE2 trade search.',
      'Added PoE2 waystone price checking by tier and item properties.',
      'Fixed relics not price checking.',
      'Improved price checking for quarterstaves.',
      'Fixed PoE2 tablets not price checking.',
      'Fixed PoE2 charm mods not showing in the price checker.',
      'Fixed PoE2 elemental damage not accumulating in weapon DPS due to PoE1/PoE2 clipboard differences.',
      'Fixed your PoE2 character lurching when a hotkey fired by releasing the movement key first.',
      'Fixed online filter sync and allowed skipping the filter directory.',
      'Fixed errors when launching a game you had not set up yet by giving it default profiles.',
      'Fixed the Linux AppImage artifact name.',
    ],
  },
  {
    version: '0.9.9',
    notes: [
      'Expanded the plugin SDK - plugins can now read the live game log (zones, deaths, whispers, and more) and open their own pop-out overlay windows, not just a tab.',
      "You can now bind a plugin's hotkeys straight from the Plugins settings box, mirrored with the Macros tab.",
      'Added adaptive price-check defaults - Scalpel learns which stat mods you usually keep or drop for each kind of item and pre-selects them for you. Set it to Eager, Conservative, or Off under Trade settings.',
      'Added profiles - save a named setup of filter, league, and trade settings per character or league and switch between them in settings. Switching games still prompts a relaunch.',
      'Added distance rulers and radius to the whiteboard so maybe you precious non-streamers can get some use out of my product bloat.',
      'Added an option to start Scalpel minimized to the tray.',
      'Added Alt and Shift modifiers for scrolling between tabs.',
      'Added accessibility text labels for currency, off by default.',
      'Added support-development buttons in Settings > General.',
      'Expanded the bug report diagnostics with additional context.',
      'Added a tooltip on the filter page clarifying that online filters need to be loaded the same way.',
      'Improved the onboarding steps.',
      'Fixed PoE2 pinning the item description when hotkeying (thanks kvan).',
      'Fixed low iLvl gear defaulting to a leveling area level instead of endgame.',
      'Fixed gem sockets in the price checker to follow the correct 2x3 layout.',
      'Fixed the Linux overlay not registering clicks on hover (X11).',
      'Fixed stacked items showing the wrong filter block when hotkeying the same item at a different stack size.',
      'Updated FAQs',
    ],
  },
  {
    version: '0.9.8',
    notes: [
      'Added Path of Exile 2 unique pricing via poe.ninja (thanks kvan for the API).',
      'Added a plugin system - install third-party overlay-tab plugins from the in-app registry (or a custom one).',
      'Added theme customization, make your Scalpel look good. or bad.',
      'Added experimental Linux (AppImage) support, running under XWayland.',
      "Added separate PoE1 and PoE2 onboarding so each game's filter, league, and trade settings are set up independently.",
      'Added a "Use Current Zone" toggle that applies zone level to the displayed item in filter.',
      'Added ability to pin current zone cheat sheets in PoE2',
      "Added Whiteboard via in-app macro. This one is super cool and I don't know how to promote it in the app yet.",
      'Added trade fetch support in the price-check and maps tabs.',
      'Added a price trend sparkline on poe.ninja price hover.',
      'Added a match count to the top of trade search results, not just the bottom.',
      'Added a filter-visibility indicator to uniques in the Dust tab so you can see which ones your filter shows.',
      'Added a "Report a Bug" tray option that captures diagnostics into a shareable report. (thanks Dan for this and a ton of other infrastructure support)',
      'Added tooltips on the filter threshold sliders to clarify how they interact.',
      'Defaulted the regex Save tab to open to reduce confusion.',
      'Fixed PoE2 filter detection of uniques and corrupted variants.',
      'Fixed PoE2 pseudo totals using a weighted sum for logged-in users when a pseudo stat has no trade equivalent.',
      'Fixed PoE2 audit values defaulting to 8 decimal places.',
      'Fixed the poe.ninja deep-link for PoE2 categories.',
      'Fixed pseudo stat totals miscounting negative-resistance Eater of Worlds implicits.',
      'Fixed hotkeyed currency not matching filter rules that use item level.',
      'Fixed price checking for big-DPS items with commas.',
      'Fixed regex tags not saving unless you pressed Enter or Space.',
      'Fixed hotkeys firing outside of the game.',
      'Fixed hotkeys not firing while the overlay was active.',
      'Fixed the @last chat hotkey.',
      'Fixed overlays staying open after Path of Exile closes.',
      'Fixed the overlay becoming click-through when saving.',
      'Fixed secondary overlays not moving with the window.',
      'Fixed sister overlay not refreshing on new hotkeys or following the main overlay during drag.',
      'Fixed cheat sheets on second monitors.',
      'Fixed map name alignment in the divination card info chip.',
      'Cleaned up the Filter tab layout in Settings.',
    ],
  },
  {
    version: '0.9.7',
    notes: [
      'Added Path of Exile 2 support - game is detected automatically, switching games prompts a relaunch. Onboarding handles setting up both games or either one.',
      'Added cheat sheets - configured in settings',
      'Added PoE1 league cheat sheet starter packs & PoE2 leveling starter packs (zone layouts by @lolcohol).',
      'Added regex tab for PoE2 starting with Waystones and Custom.',
      'Added Flasks regex tab in PoE1.',
      'Added "Open in" buttons for Wiki(2), PoEDB(2), and poe.ninja, using base type for the link.',
      'Added ternary chips to price checker for corrupted, mirrored, and fractured & min/max ternary to the ilvl chip.',
      'Added "Unid" chip to all uniques in case that\'s your bag.',
      'Added pseudos for ele damage to X on non-weapons & fixed issue with str/int not feeding life/mana pseudos.',
      'Added private league support in settings.',
      'Added a View tab in settings and put the new hide-tab feature in there.',
      'Added immediate update check when switching to beta channel.',
      "Added volume slider for your sensitive lil' ears.",
      'Added which uniques can come from a base type on filter page.',
      'Added purchase button to dust explorer.',
      'Added additional trade settings.',
      'Made audit tier a temporary tab, as it cleans up the general UX.',
      'Fixed default label colors not carrying through continue blocks.',
      'Fixed Vorici socket recolor using clipboard attributes instead of base type attributes.',
      'Fixed cluster jewel pricing defaults.',
      'Fixed API timeout modal breaking at scales.',
      'Fixed unique beasts, Inscribed Ultimatums, Forbidden Shako & other mod lines not price checking.',
      'Fixed poe.ninja prices to show linked uniques and leveled/quality gem values.',
      'Fixed some base types having incorrect inventory slots and sockets.',
      'Fixed base type not enabling memory strands in price checker.',
      'Fixed numbers-based regex not matching poe.re exactly.',
      'Fixed "both" in trade settings sending "any" to trade site.',
      "Fixed thresholds being collapsible when they shouldn't be.",
      'Fixed overlay underlay leaving a remnant if you exited mid-drag.',
    ],
  },
  {
    version: '0.9.6',
    notes: [
      'Major changes to tier section in filter page',
      'Audit page ux improvements',
      'Added support for showing related items for certain items like fragments etc.',
      'Added settings chip when price checking to adjust search parameters on the fly',
      'Added setting to price checker to change default display of results',
      'Updated meter that displays api timeouts in price checker and made warnings... exist',
      'Attempted to return clipboard data after item and regex hotkeys',
      'Improved search, more items and much, much faster',
      'Added custom scaling button (Thanks KnoT)',
      'Added crit chance and attack speed accumulators to price checker (off by default)',
      'Added warning to map searching about too many results making travel to hideout button not work well. Just the way it be.',
      'Added option in settings to decide where Scalpel mounts by default',
      'Made Faustus a jerk',
      'Fixed issue with alt-tabbing for some users (Thanks Pandas)',
      'Added crafted mods to empty affix count in price checker chip (big brains ailu)',
      'Fixed more bugs with price checker',
      'Fixed bug where esc key outside poe could cause poe to focus',
      'Fixed issue where Scalpel would appear on top of login screen',
      'Added bugs',
    ],
  },
  {
    version: '0.9.5',
    notes: [
      'Added regex tab powered by poe.re. Starting with Map & Custom',
      'Added macro in settings to hotkey most recent regex or any "macro" tagged regex',
      'Added feature to quickly input decent numbers in non filled price check fields on click',
      'Added scrubber inputs to price checker',
      'Added ability to load more items in trade results windows',
      "Added 3 trade settings: default to base, never auto-search, and don't hide mods",
      'Added "base" to unique and corrupted stretching the definition of base but it works nicely',
      'Added tiers and roll ranges to price checker rows',
      'Added color hints to unique roll ranges and fixed low value inputs',
      'Moved history tab to settings',
      'Added error banner for hotkey collisions',
      'Added warning banner for poe hotkeys like ctrl+f',
      'Added hotkey to close scalpel',
      'Added search to empty filter page - you can now update gold on your filter',
      'Fixed issue where price check tab could be clicked when there was no data',
      'Fixed so many stupid price checker item lines - hey Greg why is supported by Chance To Bleed 3 different trade inputs',
    ],
  },
  {
    version: '0.9.4',
    notes: [
      'Fixed every reported price checking issue (contracts, beasts, 2 line fractures, map implicits, foulborn mods, more)',
      'Added dust value to price checker for uniques',
    ],
  },
  {
    version: '0.9.3',
    notes: [
      "Changed update process to allow electron updates so we aren't stuck on an old version",
      'Added beta update channel for the brave & patient',
    ],
  },
  {
    version: '0.9.1h',
    notes: ['Fixed awful bug with poe2 compatibility causing interface to become completely nonfunctional in poe1'],
  },
  {
    version: '0.9.1g',
    notes: [
      'Updated the way PoE windows are detected to prevent firing in the wrong game',
      'Fixed another z-index issue if the windowed settings was open',
    ],
  },
  {
    version: '0.9.1f',
    notes: ['Fixed hotkeys getting stuck and right side keys in hotkey issues, you know, maybe'],
  },
  {
    version: '0.9.1e',
    notes: ['Fixed issue with right modifiers not releasing'],
  },
  {
    version: '0.9.1d',
    notes: [
      'Fixed issue with certain hotkey combos breaking macros',
      'Fixed issue with held keys not being restored after hotkeys',
      "Fixed issue with windows toolbar hiding in borderless fullscreen no you aren't crazy",
    ],
  },
  {
    version: '0.9.1c',
    notes: [
      "Fixed issue price checking items that don't have tiers on mods",
      'Fixed hotkeys now not working outside of the game, always something, amazing',
    ],
  },
  {
    version: '0.9.1',
    notes: [
      'Added tiers and advanced mods to price check results',
      "Reworked how negative mods get defaulted to min/max based on if they're beneficial or not but it's a judgement call",
      'Added stack pricing support',
      'Added support for price checking facetors',
      'Added "Base" chip to non-mirrored/corrupted/unique that searches for the item base',
      'Moved socket details to rows in price checker because who really cares',
      "Settings panel split into tabs so I don't hate it",
      'Overlay scale changed from slider to preset buttons',
      'Added auto-submit/press enter toggle per chat macro',
      'Added ability to bind more hotkeys to other app tabs',
      'Totally reworked hotkeying and chat macros',
      'Added warning when price checking items that are best sold on Faustus',
      'Fixed chronicle of atzoatl room price check',
      'Fixed issue with fractured mods not showing on items in trade results',
      'Fixed issue with +X for Y mods rolling into pseudos improperly for price checker',
      'Fixed crash when retiering all items out of a tier block (Thanks Liemander)',
      'Fixed empty tiers not being navigable or usable as retier targets, removed "rest" as usable tier',
      "Fixed issue with some gems not exact searching and transfigured gems work now so that's nice",
      'Fixed issue with implicit defaults in price check being poorly prioritized',
      'Fixed crafted mods acting like regular mods when price checking. Silly crafted mods.',
      'Fixed implicit modifiers that multiply affixes',
      'Updated FAQ',
    ],
  },
  {
    version: '0.9.0',
    notes: [
      'Scalpel is now open source and distributed via GitHub',
      'Fixed issue with pricing socketed gems are supported by lines',
    ],
  },
  {
    version: '0.8.4',
    notes: [
      'Fixed a bunch of broken price check stuff (Nightmare maps, 2 line mods, mods that specify sizes, keystones, skills, negative mods, flask mods, etc. It was exhausting and not exhaustive)',
      'Fixed Searing Exarch / Eater of Worlds implicits not appearing in price checker',
      'Added transfigured gem chip to price checker',
      'Added Expedition Logbook faction and boss chips',
      'Divination cards that are corrupted no longer search by corrupted',
    ],
  },
  {
    version: '0.8.3',
    notes: ['Fixed fractured items not being searchable because I am a bonehead'],
  },
  {
    version: '0.8.2',
    notes: [
      'Fixed overlay getting stuck behind PoE after alt-tabbing (big thanks to Pandas for helping debug this)',
      'Added div card outlier detection for map EV calculations (auto-flags suspicious prices, manual flag button per card)',
      'Fixed negative mod values not appearing in price checker',
      'Fixed Blighted Incubator falling to wrong filter tier',
    ],
  },
  {
    version: '0.8.1',
    notes: [
      'Added stash tab scrolling (Ctrl + Scroll Wheel to switch tabs, on by default)',
      'Added chaos/divine exchange rate chip with hover tooltip showing tenth-of-divine conversions',
      'Added timeless jewel pricing with seed and leader chips (Any Leader / specific leader toggle)',
      'Fixed chat command hotkeys garbling messages when using key combos (sorry, I tested these with function keys)',
      'Fixed multi resist mods not applying to pseudo ele res calcs in price checker',
    ],
  },
  {
    version: '0.8.0',
    notes: [
      'Price checker updates (rarity chip, fractured chip, fixed valdos, added blueprint wing count, updated map defaults)',
      'Fixed setting for "Chaos orb equivalent" not working',
      'Filter fixes (temple mods, fractures)',
      'Fixed bad bug where overlay stopped appearing with filter hotkey after switching zones',
      'Added FAQ button to overlay settings',
      'Updated FAQ',
    ],
  },
  {
    version: '0.7.9',
    notes: [
      'Scarab tiering fix',
      "Warning message when Scalpel can't read items (usually means PoE is running as admin)",
      'Fixed hotkey modifier release crash from globalShortcut refactor',
    ],
  },
  {
    version: '0.7.8',
    notes: [
      'Added memory strand breakpoint slider for adjusting strand thresholds',
      'Fixed a some items not finding their correct tier block in the filter (6 links, memory strands, some qualitied items)',
      'Fixed some price checker things not working correctly (socketed gem supports, blueprints)',
      "Fixed tier dropdown showing for items tiered by stack size when it didn't make sense (e.g. Simulacrum Splinters)",
      'Added collapsible item hero that sticks to the top with save button when scrolling',
      'Fixed audit tab kicking back to filter tab when retiering items',
      'Added defense values and DPS in price check listing dropdowns',
      'Fractured mods now also show an unfractured version (disabled) for price comparison',
    ],
  },
  {
    version: '0.7.7',
    notes: [
      'Fixed tier dropdown showing for items tiered by stack size (Simulacrum Splinters, Gold, etc.)',
      'Added buyout price currency setting (chaos/divine or chaos equivalent)',
    ],
  },
  {
    version: '0.7.6',
    notes: [
      'Added FAQ page in settings for common issues and tips',
      "Added custom chat command hotkeys in settings as I couldn't think of a better place. This page is approaching too big.",
      'Fixed issue with hotkeys not suppressing in game events',
      'Fixed mirrored chip in pricing',
    ],
  },
  {
    version: '0.7.5',
    notes: [
      'Huge speed improvement on price checker, removed some delays that were unnecessary.',
      'Fixed some items that were matching to incorrect tiers - there are more of these that are wrong so please help by reporting',
      'Boss invitations, logbooks, incubators and div cards now use regular trade search instead of bulk',
      'Updated some trade defaults - collapsed listing, chaos/div. The basic stuff.',
      'Added trade API rate limit bar with smooth step-down decay',
    ],
  },
  {
    version: '0.7.4',
    notes: [
      'Totally reworked how filters update from your online filterblade update. Now, when you make filter updates in Scalpel those are recorded to a log and "replayed" when you update your filter. This should be much much more resilient.',
      'Custom sound support, now you can apply any mp3 in your filter folder to a sound.',
      'Added weapon DPS calculations to price checker',
      'Weapon and armour stats are normalized to 20% quality (duh)',
      'Added configurable default search percentage in settings',
      'Added "Exact Values" chip to instantly set all search filters to actual roll values',
      'Fixed abyssal socket search',
      'Fixed color picker positioning bug that made it effectively unusable',
      'Gem level and quality are now adjustable rows instead of chips',
      'Unid unique candidates are now pulled from poe.ninja at runtime and cached locally',
    ],
  },
  {
    version: '0.7.3',
    notes: ['Added ability to drag and drop the overlay around and snap to sides'],
  },
  {
    version: '0.7.2',
    notes: [
      'Fixed bug where hotkeying an item that could not be audited while on the audit tab would cause a crash, imagine that',
    ],
  },
  {
    version: '0.7.0',
    notes: [
      'FilterScalpel is now just Scalpel, I think it does a better job of not limiting the scope of the tool',
      'Totally refactored updates, app now pulls MUCH smaller package for updates, and auto-reloads!',
      'Added bulk exchange pricing for currency, scarabs, fragments, essences, fossils, div cards, and all stackable items. Greg give me access to Faustus',
      'Gem pricing fixed',
      'Map pricing fixed',
      'Cluster jewel pricing fixed',
      'Fractured mods pricing fixed',
      'Influenced items pricing fixed',
      'Memory Strands pricing fixed',
      'Open prefix/suffix pricing which is something I think matters a lot',
      'Unid unique pricing fixed',
      'Trade listing type added to settings (all vs instant)',
      'Improved UX in price checker greatly',
      "Play button for alert sound preview in filter editor, you're welcome",
      'Mounts to stash side when hotkeying from stash',
      'Added automatic scaling based on resolution. I game on 1080p lmao.',
      'We now have too many settings so i reorganized them',
      'Added trade to onboard',
    ],
  },
  {
    version: '0.6.2',
    notes: ['Added alpha and I mean ALPHA price checker. Use at your own risk.'],
  },
  {
    version: '0.6.1',
    notes: [
      "Polished the div card explorer so that I don't hate the UI",
      'Added div card results to the item hero',
      'Fixed overlay flickering when moving mouse in and out of the overlay?? I hope.',
    ],
  },
  {
    version: '0.6.0',
    notes: [
      'Added v1 of the Div Card explorer to find out scrying strategies and retier div cards',
      'Div cards now show their artwork',
      'Fixed tier switching dropdown not working',
    ],
  },
  {
    version: '0.5.6',
    notes: [
      'Fixed some items not matching the correct filter tier (Blight-ravaged maps, exotic tiers)',
      'Fixed overlay blocking clicks on other windows when alt-tabbing and tried to make transitions back smoother, less flickering',
    ],
  },
  {
    version: '0.5.5',
    notes: [
      "Added overlay scale setting for larger monitors (or make it smaller, I'm not your dad)",
      'Fixed issue with OS focus changing when moving the cursor in and out of the overlay (Thanks Fezalion)',
      'Tried to fix issue with dust tab loading in empty if API calls failed for pricing',
      'Fixed bug where settings were not synced (Thanks Fezalion, again)',
      'Added slickness',
    ],
  },
  {
    version: '0.5.3',
    notes: [
      'Updated UX of audit tier again to make it even easier to use',
      "Fixed bug where overlay wouldn't work in windowed mode. Note: FS will not work in fullscreen, so use borderless.",
    ],
  },
  {
    version: '0.5.2',
    notes: ['Bugfix: Overlay now works on devices that scale DPI (Thanks @Guitaraholic)'],
  },
  {
    version: '0.5.0',
    notes: [
      'Changed UX of tier audit based on streamer feedback',
      'Added tool to explore dust values',
      'Tried to make states more persistent across tabs',
      'Esc now closes the overlay',
      'Tried to make the sliders scale using log so they feel correct',
      'Even more UX/UI updates to make everything feel consistent across tabs',
    ],
  },
  {
    version: '0.4.4',
    notes: ['Added socket recoloring tool idk why I just wanted to'],
  },
  {
    version: '0.4.3',
    notes: [
      'Tried to fix all uniques, there are lots of exceptions to try and fall through to.',
      'Added dust/disenchant values for uniques. Will calculate based on quality and other things. Should be accurate.',
      'Added dust slider to uniques but this added a new challenge - being able to filter by both at the same time. I added an and/or selector to adjust how you filter. Hope the UX is clear enough.',
      'UI/UX improvements',
      'Default hotkey changed to Ctrl+Shift+D, as Ctrl+F is the in game default for searching stash, which breaks the tool. Whoops.',
    ],
  },
  {
    version: '0.4.2',
    notes: ['Added support for maps, what a pain!'],
  },
  {
    version: '0.4.1',
    notes: ['Made auditing UX more clear based on feedback'],
  },
  {
    version: '0.4.0',
    notes: [
      'Major update: Added new tab, tier audit, which allows you to easily change the tier of multiple items at once based on their current price on ninja.',
      "Fixed issue with effects not showing up when they didn't have a sound or map icon",
      'Maybe fixed the issue with menus not being clickable when not on the overlay',
      'No more desktop icon, my bad',
    ],
  },
  {
    version: '0.3.3',
    notes: [
      'Major update: Added ability to merge changes from your online filters to your local ones. This allows you to sync economy updates or changes made on FilterBlade with your local filter and keep the changes you made.',
      'UI/UX improvements',
      'Bug fixes',
    ],
  },
  {
    version: '0.3.2',
    notes: [
      'Added support for online filters, which are then copied locally',
      'Split onboarding filter step into folder selection + filter selection',
      'Made the UI a more pleasant and consistent feeling experience',
    ],
  },
  {
    version: '0.3.0',
    notes: [
      'Added onboarding',
      'Added standalone settings menu - will add more things outside of overlays',
      'Added app update detection & in-app updating',
      'Bug fixes: flickering/multiple click closing, overlay not clickable after alt-tab, filter file not changing',
    ],
  },
  {
    version: '0.2.2',
    notes: ['Fixed issue with quality and stack size incrementing'],
  },
  {
    version: '0.2.1',
    notes: ['Added support for qualitied item thresholds'],
  },
  {
    version: '0.2.0',
    notes: [
      'Filter versioning with auto-save and checkpoints',
      'Undo/redo for filter edits',
      'CustomAlertSound support for custom sound packs',
      'Reload-on-save setting for deferred filter reload',
      'Various UI polish and styling improvements',
    ],
  },
  { version: '0.1.0', notes: ['Initial Release'] },
]
