// Generated by scripts/build-native-plugin-example.mjs. Do not edit.

// plugin-service-examples/native-item-analyzer/src/plugin.ts
function itemParams(item) {
  return {
    name: item.name,
    baseType: item.baseType,
    rarity: item.rarity,
    itemLevel: item.itemLevel,
    implicits: item.implicits,
    explicits: item.explicits
  };
}
var activate = (ctx) => {
  ctx.registerTab({
    label: "Native Item Analyzer",
    icon: '<svg viewBox="0 0 16 16"><path d="M3 2h7l3 3v9H3z" fill="none" stroke="currentColor"/><path d="M6 8h4M6 11h4" stroke="currentColor"/></svg>',
    render(container) {
      container.innerHTML = `
        <section style="padding:16px;display:grid;gap:12px">
          <h2 style="margin:0">Native Item Analyzer</h2>
          <p style="margin:0">Open the pop-out overlay, hover an item in Path of Exile, and analyze it through Rust.</p>
          <button type="button" data-open-native-overlay>Open analyzer</button>
        </section>
      `;
      const button = container.querySelector("[data-open-native-overlay]");
      const open = () => ctx.openOverlay();
      button.addEventListener("click", open);
      return () => button.removeEventListener("click", open);
    }
  });
  ctx.registerOverlay(
    {
      title: "Native Item Analyzer",
      hotkeyLabel: "Toggle native item analyzer",
      defaultSize: { width: 430, height: 390 },
      defaultPosition: { fracX: 0.72, fracY: 0.2 }
    },
    (container) => {
      container.innerHTML = `
        <section style="height:100%;padding:18px;box-sizing:border-box;display:grid;align-content:start;gap:12px;color:inherit">
          <header>
            <div style="font-size:11px;letter-spacing:.12em;text-transform:uppercase;opacity:.62">Rust sidecar</div>
            <h2 style="margin:3px 0 0">Hovered Item Analyzer</h2>
          </header>
          <p style="margin:0;opacity:.78">Hover an item in-game, then ask the supervised native backend to fingerprint its core data and count its modifiers.</p>
          <button type="button" data-analyze-item>Analyze hovered item</button>
          <div data-analysis-status style="min-height:20px;opacity:.75">Ready.</div>
          <dl data-analysis-result style="display:none;grid-template-columns:auto 1fr;gap:7px 12px;margin:0;padding:12px;border:1px solid color-mix(in srgb,currentColor 22%,transparent);border-radius:6px">
            <dt>Item</dt><dd data-result-name style="margin:0"></dd>
            <dt>Modifiers</dt><dd data-result-mods style="margin:0"></dd>
            <dt>Numbers</dt><dd data-result-numbers style="margin:0"></dd>
            <dt>Fingerprint</dt><dd data-result-fingerprint style="margin:0;font-family:monospace;overflow-wrap:anywhere"></dd>
          </dl>
        </section>
      `;
      const button = container.querySelector("[data-analyze-item]");
      const status = container.querySelector("[data-analysis-status]");
      const result = container.querySelector("[data-analysis-result]");
      const analyze = async () => {
        button.disabled = true;
        status.textContent = "Reading hovered item...";
        result.style.display = "none";
        try {
          const item = await ctx.copyAndEvaluateItem({ showOverlay: false, dispatch: false });
          if (!item) throw new Error("No recognizable item is currently hovered.");
          status.textContent = "Waiting for Rust backend...";
          const analysis = await ctx.native.call("analyzeItem", itemParams(item));
          container.querySelector("[data-result-name]").textContent = analysis.displayName;
          container.querySelector("[data-result-mods]").textContent = String(analysis.totalMods);
          container.querySelector("[data-result-numbers]").textContent = String(analysis.numericTokens);
          container.querySelector("[data-result-fingerprint]").textContent = analysis.fingerprint;
          result.style.display = "grid";
          status.textContent = "Analysis complete.";
        } catch (error) {
          status.textContent = error instanceof Error ? error.message : String(error);
        } finally {
          button.disabled = false;
        }
      };
      button.addEventListener("click", analyze);
      return () => button.removeEventListener("click", analyze);
    }
  );
};
var plugin_default = activate;
export {
  plugin_default as default
};
