import {
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
  mkdirSync,
  appendFileSync,
  symlinkSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { pathToFileURL } from 'node:url'
import { isInvokedAsMain, runScalpelPlugin } from '../src/plugin-tools/cli/scalpel-plugin.mjs'

const temporaryDirectories = []

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) rmSync(directory, { recursive: true, force: true })
})

describe('scalpel-plugin', () => {
  it('detects the main module when argv[1] reaches it through a symlink', () => {
    const root = mkdtempSync(join(tmpdir(), 'scalpel-plugin-bin-'))
    temporaryDirectories.push(root)
    const realDir = join(root, 'real')
    const linkDir = join(root, 'link')
    mkdirSync(realDir)
    writeFileSync(join(realDir, 'entry.mjs'), '')
    symlinkSync(realDir, linkDir, 'junction')
    const moduleUrl = pathToFileURL(join(realDir, 'entry.mjs')).href

    expect(isInvokedAsMain(join(linkDir, 'entry.mjs'), moduleUrl)).toBe(true)
    expect(isInvokedAsMain(join(realDir, 'entry.mjs'), moduleUrl)).toBe(true)
    expect(isInvokedAsMain(join(realDir, 'other.mjs'), moduleUrl)).toBe(false)
    expect(isInvokedAsMain(undefined, moduleUrl)).toBe(false)
  })

  it('generates, checks, bundles, and packages a generic plugin project', async () => {
    const project = mkdtempSync(join(tmpdir(), 'scalpel-plugin-cli-'))
    temporaryDirectories.push(project)
    mkdirSync(join(project, 'proto'))
    mkdirSync(join(project, 'src'))
    writeFileSync(
      join(project, 'proto/service.proto'),
      'syntax = "proto3"; package example.v1; service Example { rpc Run(RunRequest) returns (RunResponse); } message RunRequest { string value = 1; } message RunResponse { string value = 1; }\n',
    )
    writeFileSync(
      join(project, 'src/plugin.ts'),
      "import { useState } from 'react'; export default function activate() { return useState(0) }\n",
    )
    writeFileSync(
      join(project, 'manifest.json'),
      JSON.stringify({
        manifestVersion: 1,
        id: 'cli-example',
        version: '1.0.0',
        name: 'CLI Example',
        description: 'test',
        author: 'test',
        scalpelMinVersion: '>=1.0.0',
        api: { version: '1.0.0', contract: 'api.binpb', service: 'example.v1.Example' },
      }),
    )
    writeFileSync(
      join(project, 'package.json'),
      JSON.stringify({
        type: 'module',
        scalpelPlugin: {
          manifest: 'manifest.json',
          entry: 'src/plugin.ts',
          contracts: [
            {
              source: 'proto',
              descriptor: 'api.binpb',
              generated: 'src/generated',
              service: 'example.v1.Example',
            },
          ],
        },
      }),
    )

    await runScalpelPlugin('generate', project)
    await runScalpelPlugin('build', project)
    await runScalpelPlugin('check', project)
    await runScalpelPlugin('pack', project)

    expect(existsSync(join(project, 'api.binpb'))).toBe(true)
    expect(existsSync(join(project, 'src/generated/service_pb.ts'))).toBe(true)
    expect(existsSync(join(project, 'dist/manifest.json'))).toBe(true)
    const bundle = readFileSync(join(project, 'plugin.js'), 'utf8')
    expect(bundle).toContain('Generated by scalpel-plugin')
    expect(bundle).toContain('from"react"')
    expect(bundle).not.toContain('useState(0)')

    appendFileSync(join(project, 'src/generated/service_pb.ts'), '// stale\n')
    await expect(runScalpelPlugin('check', project)).rejects.toThrow(/stale/)
  }, 60_000)

  it('rejects output directories outside the plugin project', async () => {
    const project = mkdtempSync(join(tmpdir(), 'scalpel-plugin-paths-'))
    temporaryDirectories.push(project)
    writeFileSync(
      join(project, 'package.json'),
      JSON.stringify({
        scalpelPlugin: {
          contracts: [{ source: 'proto', descriptor: 'api.binpb', generated: '' }],
        },
      }),
    )

    await expect(runScalpelPlugin('generate', project)).rejects.toThrow(/non-empty path/)
  })
})
