// PoE2 clipboard fixtures shared by the trade-query golden tests and the stream price-check tests.

export const ringText = [
  'Item Class: Rings',
  'Rarity: Rare',
  'Blood Band',
  'Gold Ring',
  '--------',
  'Requires: Level 62',
  '--------',
  'Item Level: 83',
  '--------',
  '{ Implicit Modifier }',
  '11(6-15)% increased Rarity of Items found (implicit)',
  '--------',
  '{ Prefix Modifier "Virile" (Tier: 1) -- Life }',
  '+72(70-84) to maximum Life',
  '{ Suffix Modifier "of the Volcano" (Tier: 2) -- Elemental, Fire, Resistance }',
  '+36(31-35)% to Fire Resistance',
].join('\n')

export const bodyArmourText = [
  'Item Class: Body Armours',
  'Rarity: Rare',
  'Doom Shell',
  "Falconer's Jacket",
  '--------',
  'Evasion Rating: 542 (augmented)',
  'Energy Shield: 203 (augmented)',
  '--------',
  'Requires: Level 70, 60 Dex, 60 Int',
  '--------',
  'Item Level: 80',
  '--------',
  '{ Prefix Modifier "Sanguine" (Tier: 2) -- Life }',
  '+95(90-99) to maximum Life',
  '{ Suffix Modifier "of the Volcano" (Tier: 2) -- Elemental, Fire, Resistance }',
  '+36(31-35)% to Fire Resistance',
  '{ Suffix Modifier "of the Glacier" (Tier: 2) -- Elemental, Cold, Resistance }',
  '+31(31-35)% to Cold Resistance',
].join('\n')

export const bowText = [
  'Item Class: Bows',
  'Rarity: Rare',
  'Doom Thirst',
  'Warmonger Bow',
  '--------',
  'Physical Damage: 50-100',
  'Elemental Damage: 1-20 (augmented), 5-89 (augmented)',
  'Critical Hit Chance: 5.00%',
  'Attacks per Second: 1.40',
  '--------',
  'Requires: Level 60, 100 Dex',
  '--------',
  'Item Level: 80',
  '--------',
  '{ Prefix Modifier "Tempered" (Tier: 3) -- Damage, Physical }',
  '+18(15-20)% increased Physical Damage',
  '{ Suffix Modifier "of Haste" (Tier: 2) -- Attack, Speed }',
  '12(11-13)% increased Attack Speed',
].join('\n')

export const jewelText = [
  'Item Class: Jewels',
  'Rarity: Magic',
  'Fanatical Emerald of Renewal',
  '--------',
  'Item Level: 80',
  '--------',
  '{ Prefix Modifier "Fanatical" (Tier: 2) }',
  '+12(10-13)% increased Skill Speed',
  '{ Suffix Modifier "of Renewal" (Tier: 3) }',
  '+5(4-6) to maximum Mana',
  '--------',
  'Place into an allocated Jewel Socket on the Passive Skill Tree.',
].join('\n')

export const uniqueText = [
  'Item Class: Rings',
  'Rarity: Unique',
  "Ventor's Gamble",
  'Gold Ring',
  '--------',
  'Requires: Level 20',
  '--------',
  'Item Level: 80',
  '--------',
  '{ Implicit Modifier }',
  '10(6-15)% increased Rarity of Items found (implicit)',
  '--------',
  '+40(30-50) to maximum Life',
  '+25(20-30)% to Fire Resistance',
].join('\n')

export const flaskText = [
  'Item Class: Life Flasks',
  'Rarity: Magic',
  'Bubbling Transcendent Life Flask of the Plentiful',
  '--------',
  'Quality: +20% (augmented)',
  'Recovers 1008 (augmented) Life over 4 Seconds',
  '--------',
  'Item Level: 50',
  '--------',
  '{ Prefix Modifier "Bubbling" (Tier: 1) }',
  '29(28-30)% of Recovery applied Instantly',
  '{ Suffix Modifier "of the Plentiful" (Tier: 4) }',
  '41(39-46)% increased Charges',
  '--------',
  'Right click to drink. Can only hold charges while in belt.',
].join('\n')

export const FIXTURES: Record<string, string> = {
  ring: ringText,
  armour: bodyArmourText,
  bow: bowText,
  jewel: jewelText,
  unique: uniqueText,
  flask: flaskText,
}

export const STAT_ENTRIES = [
  { id: 'explicit.stat_life', text: '# to maximum Life', type: 'explicit' },
  { id: 'explicit.stat_mana', text: '# to maximum Mana', type: 'explicit' },
  { id: 'explicit.stat_fire', text: '#% to Fire Resistance', type: 'explicit' },
  { id: 'explicit.stat_cold', text: '#% to Cold Resistance', type: 'explicit' },
  { id: 'explicit.stat_phys', text: '#% increased Physical Damage', type: 'explicit' },
  { id: 'explicit.stat_aspd', text: '#% increased Attack Speed', type: 'explicit' },
  { id: 'explicit.stat_skillspeed', text: '#% increased Skill Speed', type: 'explicit' },
  { id: 'explicit.stat_charges', text: '#% increased Charges', type: 'explicit' },
  { id: 'implicit.stat_rarity', text: '#% increased Rarity of Items found', type: 'implicit' },
  { id: 'explicit.stat_rarity', text: '#% increased Rarity of Items found', type: 'explicit' },
]
